language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  # create snakemake env
  - conda create -q -n snakemake snakemake python=$TRAVIS_PYTHON_VERSION
  # download minimal kraken DB from https://doi.org/10.5281/zenodo.1343461
  - wget https://zenodo.org/record/1343462/files/kraken-test-db.tar.bz2?download=1 -O - | tar -C .test -xj 


script:
  - source activate snakemake
  # run the workflow
  - snakemake --use-conda --directory .test
